'use client'
import './globals.css'
import { Inter } from 'next/font/google'
import Navigation from '@/app/(main site)/Navigation/page'
import { ThemeProvider, createTheme } from '@mui/material/styles';
import About from './About/page';
import Container from '@mui/material/Container';
import { Providers } from './providers'; //added 9/1/2023 everything that says providers in this doc

const theme = createTheme({
  palette: {
    primary: {
      light: '#757ce8',
      main: '#311b92',
      dark: '#002884',
      contrastText: '#fff',
    },
    secondary: {
      light: '#ff7961',
      main: '#880e4f',
      dark: '#ba000d',
      contrastText: '#000',
    },
  },
  
});

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <html lang="en">
      {/* <body className="bg-blue-500"> */}
        <body className='h-[6000px]'>
      <Container maxWidth="xl" >

        <ThemeProvider theme={theme}>

              <Navigation/> 
              {/* <Sidebar/> */}
   </ThemeProvider>
   </Container>

   <Providers>{children}</Providers>

   </body>

    </html>
  )
}
